### PR TITLE
Enables and adds headers

### LINKED ISSUE #25: Add license headers

### PR DESCRIPTION
**Pull request by ignasi35**
Fixes #25

### CODE REVIEW

**Comment by ignasi35** [comment]
> it hasn't been necessary for years

TIL

**Comment by ignasi35** [comment]
- [ ] the :_* is no longer necessary (it hasn't been necessary for years!!)
- [ ] this looks like a good candidate for a build-local plugin, rather than manually appending settings everywhere.

**Comment by dwijnand** [comment]
I think it's a much better pattern than specifying it 5 times because it better represents intent.

**Comment by dwijnand** [comment]
I can send a chase PR for this!

**Comment by ignasi35** [comment]
> I can send a chase PR for this!

Feel free to push changes on this branch.

**Pull request merged**
